---

- name: Add mappings to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].public_ip }} {{ hostvars[item]['ansible_nodename'] }}"
    regexp: "{{ hostvars[item]['ansible_nodename'] }}$"
    state: present
  delegate_to: localhost
  run_once: true
  with_items:
    - "{{ groups['all'] }}"
  
