---
- name: Stop Ambari agent
  shell: "ambari-agent stop"
  ignore_errors: True

- name: Stop Ambari server
  shell: "ambari-server stop"
  run_once: true
  delegate_to: "{{groups['ambari-server'][0]}}"
  ignore_errors: True

- name: Install Ambari server on "{{groups['ambari-server'][0]}}"
  yum: name="ambari-server" state=present update_cache=yes
  run_once: true
  delegate_to: "{{groups['ambari-server'][0]}}"
  
- name:  Set Up the Ambari Server
  shell: "ambari-server setup -s -j {{java_home}}"
  run_once: true
  delegate_to: "{{groups['ambari-server'][0]}}"

- name: Start Ambari server
  shell: "ambari-server start"
  run_once: true
  delegate_to: "{{groups['ambari-server'][0]}}"

- name: Wait for ambari-server to launch start
  wait_for: port="8080" delay=10 timeout=120
  run_once: true
  delegate_to: "{{groups['ambari-server'][0]}}"

- name: Install Ambari agent
  yum: name="ambari-agent" state=present update_cache=yes

- name: update Ambari agent config
  lineinfile: dest=/etc/ambari-agent/conf/ambari-agent.ini regexp=^hostname= line=hostname={{groups['ambari-server'][0]}}

- name: Start Ambari agent
  shell: "ambari-agent start"
