---
# AZURE param
azure_storage_account_type: "Standard_LRS"
azure_default_location: "FranceCentral" # FranceCentral* northeurope or westeurope or FranceCentral
azure_default_vm_size: "Standard_D2_v3"
azure_vm_admin_username: "mounir"
azure_vm_admin_ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

# Cluster params
azure_resource_group: "my-resource-group-hdp"
azure_storage_account: "mystorageaccount861hdp"
azure_virtual_network: "my-virtual-network-hdp"
azure_virtual_interface: "my-virtual-interface-hdp"
azure_subnet: "my-subnet-hdp"
azure_security_group: "my-security-group-hdp"
azure_security_group_rules:
  - {port: 22, priority: 101}
  - {port: 8080, priority: 102}
  - {port: 3000, priority: 103}
  - {port: 50070, priority: 104}
  - {port: 8088, priority: 105}
  - {port: 8888, priority: 106}
  
azure_network_address_prefixes: "10.0.0.0/24"
azure_vm_image:
  {   offer: "CentOS",
      publisher: "OpenLogic",
      sku: "7.4",
      version: "latest"
  }
azure_virtual_machines: 
  - { name: "myhost-hdp-01", virtual_interface: "vir-net-hdp-01", ip_config_name: "ip-config-hdp-01", public_ip: "public-ip-hdp-01", tags: {'hdp':'','ambari-server':''}}
  - { name: "myhost-hdp-02", virtual_interface: "vir-net-hdp-02", ip_config_name: "ip-config-hdp-02", public_ip: "public-ip-hdp-02", tags: {'hdp':''}}
  - { name: "myhost-hdp-03", virtual_interface: "vir-net-hdp-03", ip_config_name: "ip-config-hdp-03", public_ip: "public-ip-hdp-03", tags: {'hdp':'','mariadb':''}}
  - { name: "myhost-hdp-04", virtual_interface: "vir-net-hdp-04", ip_config_name: "ip-config-hdp-04", public_ip: "public-ip-hdp-04", tags: {'hdp':''}}
  - { name: "myhost-hdp-05", virtual_interface: "vir-net-hdp-05", ip_config_name: "ip-config-hdp-05", public_ip: "public-ip-hdp-05", tags: {'hdp':''}}

