---

- name: Install epel-release rpm packages
  yum: name="epel-release" state=present update_cache=yes

#- name: Copy apache repo file
#  copy: src=apache-maven.repo dest=/etc/yum.repos.d/apache-maven.repo

- name: Install additionnals rpm packages
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    "{{list_yum_pkg}}"

- name: Copy ambari repo file
  template: src=ambari.repo.j2 dest=/etc/yum.repos.d/ambari.repo

- name: Copy hdp repo file
  template: src=hdp.repo.j2 dest=/etc/yum.repos.d/hdp.repo

- name: Check if selinux is disabled
  shell: "sestatus | grep \"SELinux status\""
  register: selinux_status

- name: Disable selinux from config file
  selinux: state=disabled
  when: "'disabled' not in selinux_status.stdout"

- name: Check if iptables is enabled
  stat: path=/etc/systemd/system/basic.target.wants/firewalld.service 
  register: firewalld_status

- name: Disable iptables
  command: systemctl disable firewalld
  when: firewalld_status.stat.exists

- name: Disable swap from fstab
  lineinfile:
     dest: /etc/fstab
     state: absent
     backup: yes
     regexp: swap

- name: Add motd
  template: src=motd.j2 dest=/etc/motd

- name: Check if ntpd is enabled
  stat: path=/etc/systemd/system/basic.target.wants/ntpd.service
  register: ntpd_status
  
- name: Activate ntpd
  service: name=ntpd state=started enabled=yes
  when: ntpd_status.stat.exists == False
