---
- hosts: all
  serial: "{{ serial_strategy|default(\"{{ groups['all']|length }}\")|int}}"
  roles:
    - {role: requirements, tags: [init] }
    - {role: jdk , tags: [init]}

- hosts: mariadb
  roles:
    - {role: mariadb , tags: [init]}
